obj-$(NAUT_CONFIG_HVM_HRT) += hrt/
obj-$(NAUT_CONFIG_X86_64_HOST) += x64/
obj-$(NAUT_CONFIG_XEON_PHI) += k1om/
obj-$(NAUT_CONFIG_GEM5) += gem5/
obj-$(NAUT_CONFIG_ARCH_RISCV) += riscv/
obj-$(NAUT_CONFIG_ARCH_ARM64) += arm64/
