obj-$(NAUT_CONFIG_ARCH_X86) += \
	nautilus/ \
	arch/ \
	dev/ \
	fs/  \
	gc/  \
	rt/ \
	net/ \
	acpi/ \
        compat/ \
	test/ 

obj-$(NAUT_CONFIG_ARCH_RISCV) += \
	nautilus/ \
	arch/ \
	dev/

obj-$(NAUT_CONFIG_CXX_SUPPORT) += cxx/
obj-$(NAUT_CONFIG_LEGION_RT) += legion_runtime/
obj-$(NAUT_CONFIG_LOAD_LUA) += lua_src/
obj-$(NAUT_CONFIG_RUST_SUPPORT) += rust/
obj-$(NAUT_CONFIG_ASPACES) += aspace/
obj-$(NAUT_CONFIG_ALLOCS) += alloc/
